### ISSUE TITLE
Not sure if these CAT XL work correctly

### ISSUE THREAD

**Issue by aiste-kalinauskaite** [OasisLMF/ReinsuranceTestTool#39]
3 layers:
ReinsLayerNumber = 1,2,3
% ceded = 1 on all
% placed = 0.5 on all
Inuring priority = 1,1,1
Layers:
50 xs 50
50 xs 100
50 xs 150

Joh - can you check. I was expecting 75 ceded getting 50.

**Comment by johcarter** [comment]
@aiste-kalinauskaite please could i also have your scope file

**Comment by johcarter** [comment]
I got the same result. I think it is because the fm_xref file is wrong and all three layers are not being netted.
Here is the file
output_id,agg_id,layer_id
1,1,1
2,2,1
3,3,1
4,4,1
5,5,1
6,6,1
7,7,1
8,8,1
9,9,1
10,10,1
11,11,1
12,12,1

@sambles It should be 
output_id,agg_id,layer_id
1,1,3
2,2,3
3,3,3
4,4,3
5,5,3
6,6,3
7,7,3
8,8,3
9,9,3
10,10,3
11,11,3
12,12,3

because there are 3 layers, you must put the last layer id to get losses net of all layers

**Comment by johcarter** [comment]
now fm_xref is correct but it doesn't fix the numbers. There is a potential bug in fmcalc as i found i got the same results for 2 layers as i do for 3. @bmatharu is investigating.

**Comment by johcarter** [comment]
Me to retest after ben has checked in his fix.

**Comment by johcarter** [comment]
now getting 75 total recovery for the above example. fixed
